#apiVersion: v1
#kind: ConfigMap
#metadata:
#  name: cinemaabyss-config
#  namespace: cinemaabyss
#data:
#  # Database configuration
#  DB_HOST: "postgres"
#  DB_PORT: "5432"
#  DB_NAME: "cinemaabyss"
#  DB_USER: "postgres"
#
#  # Service URLs
#  MONOLITH_URL: "http://monolith:8080"
#  MOVIES_SERVICE_URL: "http://movies-service:8081"
#  
#  # Strangler Fig configuration
#  GRADUAL_MIGRATION: "true"
#  MOVIES_MIGRATION_PERCENT: "100"



apiVersion: v1
kind: ConfigMap
metadata:
  name: cinemaabyss-config
  namespace: cinemaabyss
data:
  DB_HOST: "postgres"
  DB_PORT: "5432"
  DB_NAME: "cinemaabyss"
  DB_USER: "postgres"
  # Service URLs
  MONOLITH_URL: "http://monolith:8080"  # Уточните имя сервиса монолита, если оно другое
  MOVIES_SERVICE_URL: "http://movies-service:8081"

  EVENTS_SERVICE_URL: "http://events-service:8082"
  # Strangler Fig configuration
  GRADUAL_MIGRATION: "true"
  MOVIES_MIGRATION_PERCENT: "50"

  #Kafka configuration для Events Service(новый)
  KAFKA_BROKERS: "kafka-service:9092" # Убедитесь, что имя kafka-service совпадает с именем сервиса Kafka в K8s

