apiVersion: v1
kind: Secret
metadata:
  name: dockerconfigjson
  namespace: cinemaabyss
data:
  .dockerconfigjson: "ewoJImF1dGhzIjogeyJnaGNyLmlvIjogewoJCSAgICAiYXV0aCI6ICJZV3hwWVdKcGN6cG5hWFJvZFdKZmNHRjBYekV4UVZwRlVsVXpTVEJ5WlcxdWFEUllkbmxMYTBoZmNHdEpiR05tWVV0SWVWcFFhall4TlVwamRITTBZM1ZYTVROWk1UbFdNSEF4YkRNemNIZzRabEkwU2xkWFVqZERXRTFXTm1wbVprZFFkVkE9Igp9Cgl9LAoJImNyZWRzU3RvcmUiOiAiZGVza3RvcCIsCgkiY3VycmVudENvbnRleHQiOiAiZGVza3RvcC1saW51eCIsCgkicGx1Z2lucyI6IHsKICAgICJkZWJ1ZyI6IHsKICAgICJob29rcyI6ICJleGVjIgogICAgfSwKICAgICJzY291dCI6IHsKICAgICJob29rcyI6ICJwdWxsLGJ1aWxkeCBidWlsZCIKICAgIH0KfSwKCSJmZWF0dXJlcyI6IHsKICAgICJob29rcyI6ICJ0cnVlIgp9Cn0KCg=="
type: kubernetes.io/dockerconfigjson
