apiVersion: apps/v1
kind: Deployment
metadata:
  name: events-service
  namespace: cinemaabyss
spec:
  replicas: 1
  selector:
    matchLabels:
      app: events-service
  template:
    metadata:
      labels:
        app: events-service
    spec:
      containers:
      - name: events-service
        image: ghcr.io/<AliaBis>/events-service:latest
        ports:
        - containerPort: 8082
        envFrom: # <-- Добавьте эту секцию
        - configMapRef:
          name: cinemaabyss-config
        env:
        - name: KAFKA_BROKERS
          value: "kafka-service:9092"
---
apiVersion: v1
kind: Service
metadata:
  name: events-service
  namespace: cinemaabyss
spec:
  selector:
    app: events-service
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 8082