apiVersion: apps/v1
kind: Deployment
metadata:
  name: proxy-service
  namespace: cinemaabyss
spec:
  replicas: 1
  selector:
    matchLabels:
      app: proxy-service
  template:
    metadata:
      labels:
        app: proxy-service
    spec:
      containers:
      - name: proxy-service
        image: ghcr.io/<AliaBis>/proxy-service:latest
        ports:
        - containerPort: 8000
        envFrom: # <-- Добавьте эту секцию
        - configMapRef:
            name: cinemaabyss-config # Имя вашего ConfigMap
        env:
        - name: MONOLITH_URL
          value: "http://monolith-service:8080"
        - name: MOVIES_SERVICE_URL
          value: "http://movies-service:8081"
        - name: EVENTS_SERVICE_URL
          value: "http://events-service:8082"
        - name: MOVIES_MIGRATION_PERCENT
          value: "50"
---
apiVersion: v1
kind: Service
metadata:
  name: proxy-service
  namespace: cinemaabyss
spec:
  selector:
    app: proxy-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000