name: Docker Build and Push

on:
  workflow_dispatch:
  push:
    branches: [ main, cinema ]
    paths:
      - 'src/**'
      - '.github/workflows/docker-build-push.yml'
  release:
    types: [published]

env:
  REGISTRY: ghcr.io
  #логин и репозиторий в нижнем регистре
  IMAGE_BASE: ghcr.io/aliabis/architecture-cinemaabyss

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # 1. Monolith
      - name: Extract metadata for Monolith
        id: meta-monolith
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.IMAGE_BASE }}/monolith
          tags: |
            type=sha,format=short
            latest

      - name: Build and push Monolith
        uses: docker/build-push-action@v4
        with:
          context: ./src/monolith
          push: true
          tags: ${{ steps.meta-monolith.outputs.tags }}
          labels: ${{ steps.meta-monolith.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      # 2. Movies Service
      - name: Extract metadata for Movies
        id: meta-movies
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.IMAGE_BASE }}/movies-service
          tags: |
            type=sha,format=short
            latest

      - name: Build and push Movies Service
        uses: docker/build-push-action@v4
        with:
          context: ./src/microservices/movies
          push: true
          tags: ${{ steps.meta-movies.outputs.tags }}
          labels: ${{ steps.meta-movies.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      # 3. Proxy Service
      - name: Extract metadata for Proxy
        id: meta-proxy
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.IMAGE_BASE }}/proxy-service
          tags: |
            type=sha,format=short
            latest

      - name: Build and push Proxy
        uses: docker/build-push-action@v4
        with:
          context: ./src/microservices/proxy
          push: true
          tags: ${{ steps.meta-proxy.outputs.tags }}
          labels: ${{ steps.meta-proxy.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      # 4. Events Service
      - name: Extract metadata for Events
        id: meta-events
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.IMAGE_BASE }}/events-service
          tags: |
            type=sha,format=short
            latest

      - name: Build and push Events
        uses: docker/build-push-action@v4
        with:
          context: ./src/microservices/events
          push: true
          tags: ${{ steps.meta-events.outputs.tags }}
          labels: ${{ steps.meta-events.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
